### ISSUE TITLE
Replace Christmas banner with standard banner

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#10]

**Comment by vehrlich** [comment]
I miss proper ratio and 'source' with layers on provided logo on dropbox.
I've checked logo area, it's size is 880x407px. Size of logo on Dropbox is 1600x774. 

Should it be possible to send me proper logo ? Or I should resize it by myself (I don't guarantee the result :)

**Comment by collabradoodle** [comment]
The current banner is the Comic Contest banner. The contest is over.
