### ISSUE TITLE
Add Hebrew website 

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#13]
@vehrlich -

Add Hebrew language to Space Scoop website. Translated text can be found here (column S): https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit#gid=633367598

**Comment by vehrlich** [comment]
Need text graphic (curve in Hebrew) similar to #9

**Comment by vehrlich** [comment]
Spent some time with Illustrator trying to prepare curve from text. Without result, so I will wait for proper graphic or return to this issue after I will solve some other issues.

**Comment by vehrlich** [comment]
Lost translations, need to check against https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit#gid=633367598
