### ISSUE TITLE
Add badge to 'About' page

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#18]
@vehrlich -  Add Great Website For Kids badge to website. I don't appear able to add images. Image attached.
![1139_gws_badge_space-scoop](https://cloud.githubusercontent.com/assets/11634784/22382467/bc44f86c-e4bd-11e6-8c35-32a090c62352.jpg)

**Comment by vehrlich** [comment]
now its there. 
don't know exactly where you want it. so you can move image in administration now.

**Comment by TheTrashFactory** [comment]
@vehrlich - perfect, thanks
