### ISSUE TITLE
Link partner articles to relevant page

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#23]
@vehrlich  Arrange for Space Scoops from each partner organisation to appear on partner page. E.g. http://www.spacescoop.org/en/friends/alma/

**Comment by vehrlich** [comment]
@TheTrashFactory that means you want articles for particular partner listed on partner's page ?
Like this three put on [this](http://www.spacescoop.org/en/friends/eso/) page ?
![space scoop](https://cloud.githubusercontent.com/assets/1701829/23286124/e581b07a-fa35-11e6-8a8e-4b7062deea15.png)

**Comment by TheTrashFactory** [comment]
@vehrlich - That's right, thanks! Also with the line/link below saying "Read more Space Scoops based on ESO Press Releases."

**Comment by vehrlich** [comment]
@TheTrashFactory For now link 'Read more Space scoops based on ...' points to partner detail (e.g. http://www.spacescoop.org/en/friends/eso/ )

That mean that link from partner detail will point to the same place (partner detail).
Should I change link to scoops filtered by partner ?

**Comment by TheTrashFactory** [comment]
@vehrlich - yes please, if that's possible.
