### ISSUE TITLE
Remove 2012 Workshop banner - http://es.unawe.org

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#24]
@vehrlich

**Comment by TheTrashFactory** [comment]
Also on all other national websites: 
http://de.unawe.org
http://it.unawe.org
http://nl.unawe.org
http://za.unawe.org
http://uk.unawe.org

**Comment by vehrlich** [comment]
@TheTrashFactory This could be done in administration
e.g. http://de.unawe.org/admin/pages/page/49/
