### ISSUE TITLE
Change 'Pictures' section title

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#3]
Rename 'Pictures' section to 'Stories' to ensure audience know this section contains all Space Scoops in chronological order.

**Comment by slowe** [comment]
@TheTrashFactory Is there a Google Doc where the translations for SpaceScoop are kept? There is one for Space Awareness.

**Comment by unawe** [comment]
Yes @slowe : [](https://docs.google.com/spreadsheets/d/16A9CPyhFyOvD3ipV-mV0vjYaE5iSSEx3TJF93Hr-E7s/edit?usp=drive_web ) (P. Russo)

**Comment by unawe** [comment]
https://docs.google.com/spreadsheets/d/16A9CPyhFyOvD3ipV-mV0vjYaE5iSSEx3TJF93Hr-E7s/edit?usp=drive_web

**Comment by TheTrashFactory** [comment]
More translations for spacescoop.org can be found on ('Space Scoop website' tab): 

[https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit?usp=sharing](https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit?usp=sharing)
