### ISSUE TITLE
Add Italian language

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#4]
Italian translations of all static text available on (column E): [https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit#gid=0](https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit#gid=0)

**Comment by slowe** [comment]
@TheTrashFactory Sorry for being so slow. I just want to check I'm getting the right thing, isn't the Italian translation in column D (of the SpaceScoop sheet)?

**Comment by TheTrashFactory** [comment]
@slowe - you're right, it's column D (I was originally looking at the UNAWE sheet). Thanks for checking!

**Comment by slowe** [comment]
I finally worked out how force the update to work. However, the Italian version causes a server error. I don't know why.

**Comment by TheTrashFactory** [comment]
@slowe it's working fine for me. Thanks! I'll close this issue now
