### ISSUE TITLE
Share buttons Space Scoops are not working

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spacescoop#6]
The share buttons (Twitter, Facebook and Pinterest) of the individual Space Scoops are not working. The problem is happening for different Space Scoops and languages.

**Comment by slowe** [comment]
@jorgegrivero Do you know if they've ever been links?

**Comment by slowe** [comment]
I'm having trouble deploying Space Scoops so can't make this live. I get the following error:
TASK [ensure django uploaded directory exists] *********************************
fatal: [production]: FAILED! => {"changed": false, "failed": true, "gid": 33, "group": "www-data", "mode": "0777", "msg": "/home/web/spacescoop_uploads already exists as a link", "owner": "web", "path": "/home/web/spacescoop_uploads", "size": 36, "state": "link", "uid": 1001}

**Comment by slowe** [comment]
I commented out the lines that check for the spacescoop_uploads directory and can force an update. 

@jorgegrivero Are you happy for this issue to be closed?

**Comment by jorgegrivero** [comment]
I checked and it seems that the share buttons are still not working.

**Comment by vehrlich** [comment]
@jorgegrivero do you want to create prepared message for twitter share ? or hastags ?

Like 'Check this great spacescoop #ILoveSpace' :) It's possible according twitter codumentation https://dev.twitter.com/web/tweet-button
