### ISSUE TITLE
Update web banner

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#7]
@slowe Replace contest banner with Space Scoop Christmas/winter banner

**Comment by slowe** [comment]
@TheTrashFactory I don't have the banner. Also, I'm still waiting for @bruno-rino to help me work out why I can't update SpaceScoop.

**Comment by TheTrashFactory** [comment]
@slowe Here is the banner: https://www.dropbox.com/sh/zugr376lft031re/AACZoFnoMR9NBglcQo7qcdJXa?dl=0
Do you think you can put it online?

**Comment by collabradoodle** [comment]
@slowe For the holidays we could use the christmas banner and logo in this folder: 
[](https://www.dropbox.com/sh/2kzs9gukp9l0kwb/AADghbrGzyKI9qpiG6qVdxxUa?dl=0)

After that we can use the white banner and the moving logo.
