### ISSUE TITLE
Add Space Scoop Arabic website

### ISSUE THREAD

**Issue by TheTrashFactory** [unawe/spacescoop#9]
Add Arabic version of Space Scoop website. Arabic translations of static text can be found on Column I:
https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit#gid=633367598

**Comment by vehrlich** [comment]
I need graphic in Arabic in proper shape, color and font like this (this is for Czech language)
http://www.spacescoop.org/static/img/earthscape/earthscape-text-cs.0c2a63645171.svg

**Comment by vehrlich** [comment]
Spent some time with Illustrator trying to prepare curve from text. Without result, so I will wait for proper graphic or return to this issue after I will solve some other issues.

**Comment by vehrlich** [comment]
Lost translations, need to check against https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit#gid=633367598
